repos:
  - repo: local
    hooks:
      - id: fourmolu
        name: fourmolu
        entry: scripts/run-fourmolu.sh --mode=inplace
        language: system
        files: '\.(hs|hs-boot)$'
        exclude: |
          (?x)^(
            region-tests/(?!Main.hs)
            | fixity-tests/(?!Main.hs)
            | data/examples/
            | data/diff-tests/
            | data/parse-failures/
          )

  - repo: https://github.com/necaris/pre-commit-pyright
    rev: '1.1.53'
    hooks:
      - id: pyright

  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      # do not turn these on, to prevent merge conflicts when
      # merging upstream ormolu changes
      # - id: end-of-file-fixer
      # - id: trailing-whitespace
