name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.build_prod.outputs.version }}

jobs:
  stack_test:
    strategy:
      matrix:
        stack_yaml:
          - stack-ghc-9.0.yaml
          - stack-ghc-9.2.yaml
          # technically redundant, since this should be a symlink,
          # but just to be extra sure
          - stack.yaml

    name: 'stack_test: ${{ matrix.stack_yaml }}'
    runs-on: ubuntu-latest
    env:
      STACK_YAML: ${{ matrix.stack_yaml }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack_test-${{ matrix.stack_yaml }}-${{ hashFiles(matrix.stack_yaml, 'fourmolu.cabal') }}

      # use development mode, to enable -Werror
      - run: stack test --flag fourmolu:dev

      - name: Check that Cabal file was generated
        run: git diff --exit-code '*.cabal'

  cabal_test:
    strategy:
      matrix:
        ghc_version:
          - '9.0'
          - '9.2'

    name: 'cabal_test: ghc-${{ matrix.ghc_version }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-cache-${{ matrix.ghc_version }}-${{ hashFiles('fourmolu.cabal') }}
      - run: cabal update
      - run: cabal install --overwrite-policy=always alex happy
      - run: cabal test

  os_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    name: 'os_test: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-os_test-${{ hashFiles('stack.yaml', 'fourmolu.cabal') }}
      - run: stack test --fast

  build_haddock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build_haddock-${{ hashFiles('stack.yaml', 'fourmolu.cabal') }}

      - name: Build haddock
        # just a sanity check, so no need to build third-party docs
        run: stack haddock --fast --no-haddock-deps

      - name: Bundle haddock docs
        run: tar czf fourmolu-docs.tar.gz -C "$(find .stack-work/dist -regex '.*/doc/html/[^/]*')" .

      - uses: actions/upload-artifact@v3
        with:
          name: fourmolu-docs
          path: fourmolu-docs.tar.gz


  build_prod:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    name: 'build_prod: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build_prod-${{ hashFiles('stack.yaml', 'fourmolu.cabal') }}

      - name: Build
        run: |
          ARGS=(
              # turn on fixity-th, for production build
              --flag fourmolu:fixity-th

              # install binary to ./bin/
              --copy-bins --local-bin-path ./bin/

              # not using `dev` flag or testing; done in `stack_test` + `os_test`
          )
          stack build "${ARGS[@]}"

      - name: Get build info
        run: scripts/GetBuildInfo.hs
        id: build-info

      - name: Rename binary
        run: cp bin/fourmolu "bin/fourmolu-$version-$os-$arch"
        env:
          version: ${{ steps.build-info.outputs.version }}
          os: ${{ steps.build-info.outputs.os }}
          arch: ${{ steps.build-info.outputs.arch }}

      - name: Store binary
        uses: actions/upload-artifact@v3
        with:
          name: fourmolu-binary-${{ matrix.os }}
          path: bin/fourmolu-*

    outputs:
      version: ${{ steps.build-info.outputs.version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-lint-stack-${{ hashFiles('stack.yaml', 'fourmolu.cabal') }}
      - name: Build Fourmolu executable
        run: stack build --fast :fourmolu

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-lint-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  check_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-check_sdist-${{ hashFiles('stack.yaml') }}
      - name: Create sdist bundle
        run: stack sdist --test-tarball --tar-dir .
      - uses: actions/upload-artifact@v3
        with:
          name: fourmolu-sdist
          path: fourmolu-*.tar.gz

  check_redundant_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: scripts/clean_redundant_examples.py
      - run: git diff --exit-code data/examples/
