name: Release
on: workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - ci

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-release-cache-${{ hashFiles('make-release.sh') }}

      - uses: actions/download-artifact@v3
        with:
          name: fourmolu-binary-ubuntu-latest
          path: ./bin/
      - uses: actions/download-artifact@v3
        with:
          name: fourmolu-binary-macos-latest
          path: ./bin/

      - name: Make release
        run: scripts/make-release.sh ./bin/fourmolu-*
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ needs.ci.outputs.version }}
